#!/usr/bin/env python3
"""sprite_compile.py -- COMPILED SPRITES: every 8x16 frame becomes a
Z80 routine (org #8000, above screen buffer B) that draws itself at HL.

Per screen byte (2 Mode 0 pixels):
    both pixels solid       ld (hl),n     10 T   (vs 38 T masked)
    both transparent        inc hl         6 T
    one of each             ld a,(hl) / and mask / or data / ld (hl),a
Rows step via a shared +#7FC/wrap helper; rows that are empty to the
end of the frame simply RET early -- drips, rocks and steam cost a
fraction of a full sprite.  No stack tricks, no DI: the routine only
uses A and HL.

Usage:  python3 tools/sprite_compile.py > src/sprites_c.asm
"""
import sys

sys.path.insert(0, "tools")
from sprites_art import FRAMES


def left_pixel(pen):
    return ((pen & 1) << 7) | ((pen & 2) << 2) | ((pen & 4) << 3) | ((pen & 8) >> 2)


def right_pixel(pen):
    return left_pixel(pen) >> 1


def compile_frame(name, art):
    out = [f"{name}:"]
    rows = [[None if ch == '.' else int(ch, 16) for ch in r] for r in art]
    # trim rows that are empty through to the end of the frame
    last = 0
    for i, r in enumerate(rows):
        if any(p is not None for p in r):
            last = i
    for ri, row in enumerate(rows[:last + 1]):
        for bx in range(4):
            pl, pr = row[bx * 2], row[bx * 2 + 1]
            if pl is None and pr is None:
                out.append("        inc hl")
            elif pl is not None and pr is not None:
                v = left_pixel(pl) | right_pixel(pr)
                out.append(f"        ld (hl),#{v:02X}")
                out.append("        inc hl")
            else:
                mask = 0xAA if pl is None else 0x55
                data = right_pixel(pr) if pl is None else left_pixel(pl)
                out.append("        ld a,(hl)")
                out.append(f"        and #{mask:02X}")
                out.append(f"        or #{data:02X}")
                out.append("        ld (hl),a")
                out.append("        inc hl")
        if ri < last:
            out.append("        call spr_next_row")
    out.append("        ret")
    return out


def main():
    print("; ======================================================================")
    print("; GENERATED by tools/sprite_compile.py -- COMPILED SPRITES")
    print("; Each label is a routine: enter with HL = screen address of the")
    print("; frame's top-left byte; draws itself, trashes A and HL only.")
    print("; Lives at #8000-#A5FF: above screen buffer B, below AMSDOS space.")
    print("; ======================================================================")
    print()
    print("        org #8000")
    print()
    print("; shared row step: +#800 minus the 4 bytes just written, with the")
    print("; usual character-row wrap (see the tile blitter for the derivation)")
    print("spr_next_row:")
    print("        ld a,l")
    print("        add a,#FC")
    print("        ld l,a")
    print("        ld a,h")
    print("        adc a,#07")
    print("        ld h,a")
    print("        and #38")
    print("        ret nz")
    print("        ld a,l")
    print("        add a,#50")
    print("        ld l,a")
    print("        ld a,h")
    print("        adc a,#C0")
    print("        ld h,a")
    print("        ret")
    print()
    for name, art in FRAMES.items():
        print("\n".join(compile_frame(name, art)))
        print()
    print("sprites_c_end:")
    print("        assert sprites_c_end < #A600")


if __name__ == "__main__":
    main()
