; ======================================================================
; GENERATED by tools/level_gen.py -- DO NOT EDIT, edit the tool instead
; (the pixel data lives in levels_hi.asm, on the #A600 shelf)
; ======================================================================

; --- level_table: per level: bank byte (#C4+n), word offset
; within the bank (#4000-based), word blob length ---
level_table:
        defb #C4
        defw #4000,614   ; level 1
        defb #C4
        defw #4266,640   ; level 2
        defb #C4
        defw #44E6,640   ; level 3
        defb #C4
        defw #4766,655   ; level 4
        defb #C4
        defw #49F5,658   ; level 5
        defb #C4
        defw #4C87,643   ; level 6
        defb #C4
        defw #4F0A,646   ; level 7
        defb #C4
        defw #5190,656   ; level 8
        defb #C4
        defw #5420,673   ; level 9
        defb #C4
        defw #56C1,658   ; level 10
        defb #C4
        defw #5953,643   ; level 11
        defb #C4
        defw #5BD6,647   ; level 12
        defb #C4
        defw #5E5D,661   ; level 13
        defb #C4
        defw #60F2,667   ; level 14
        defb #C4
        defw #638D,667   ; level 15
        defb #C4
        defw #6628,664   ; level 16
        defb #C4
        defw #68C0,668   ; level 17
        defb #C4
        defw #6B5C,666   ; level 18
        defb #C4
        defw #6DF6,666   ; level 19
        defb #C4
        defw #7090,648   ; level 20
        defb #C4
        defw #7318,638   ; level 21
        defb #C4
        defw #7596,652   ; level 22
        defb #C4
        defw #7822,648   ; level 23
        defb #C4
        defw #7AAA,652   ; level 24
        defb #C4
        defw #7D36,654   ; level 25
        defb #C5
        defw #4000,664   ; level 26
        defb #C5
        defw #4298,658   ; level 27
        defb #C5
        defw #452A,651   ; level 28
        defb #C5
        defw #47B5,656   ; level 29
        defb #C5
        defw #4A45,666   ; level 30
        defb #C5
        defw #4CDF,661   ; level 31
        defb #C5
        defw #4F74,670   ; level 32
        defb #C5
        defw #5212,654   ; level 33
        defb #C5
        defw #54A0,680   ; level 34
        defb #C5
        defw #5748,662   ; level 35
        defb #C5
        defw #59DE,666   ; level 36
        defb #C5
        defw #5C78,665   ; level 37
        defb #C5
        defw #5F11,649   ; level 38
        defb #C5
        defw #619A,667   ; level 39
        defb #C5
        defw #6435,674   ; level 40
        defb #C5
        defw #66D7,653   ; level 41
        defb #C5
        defw #6964,646   ; level 42
        defb #C5
        defw #6BEA,656   ; level 43
        defb #C5
        defw #6E7A,667   ; level 44
        defb #C5
        defw #7115,659   ; level 45
        defb #C5
        defw #73A8,660   ; level 46
        defb #C5
        defw #763C,668   ; level 47
        defb #C5
        defw #78D8,664   ; level 48
        defb #C5
        defw #7B70,666   ; level 49
        defb #C6
        defw #4000,676   ; level 50
        defb #C6
        defw #42A4,664   ; level 51
        defb #C6
        defw #453C,655   ; level 52
        defb #C6
        defw #47CB,652   ; level 53
        defb #C6
        defw #4A57,668   ; level 54
        defb #C6
        defw #4CF3,661   ; level 55
        defb #C6
        defw #4F88,664   ; level 56
        defb #C6
        defw #5220,665   ; level 57
        defb #C6
        defw #54B9,663   ; level 58
        defb #C6
        defw #5750,658   ; level 59

LEVEL_COUNT     equ 59
TILE_EMPTY      equ 0
TILE_KEY_BASE   equ 8
TILE_DOOR_BASE  equ 13
TILE_MEDKIT     equ 20
TILE_SWITCH_OFF equ 23
TILE_SWITCH_ON  equ 24
TILE_VAULT      equ 25
GLYPH_SPACE     equ 37
GLYPH_KEY       equ 38
GLYPH_HEART     equ 39
GLYPH_BOLT      equ 40
GLYPH_UP        equ 41
GLYPH_DOWN      equ 42
; elevator stops, bottom terminus first
ELEV_COUNT      equ 6
elev_stops:
        defb 1,10,20,30,40,50
